### ISSUE TITLE
IPFS content sync

### ISSUE THREAD

**Issue by pentreathm** [decentraland/catalyst#1056]
Evaluate if the next strategy is possible in order to leverage a decentralized storage and release the Content servers from content that is not actively used by the clients. 

- [ ]  Move the scenes deployments history to IPFS 
- [ ] Sync the Pins between the Catalyst Servers 
- [ ] Have a way to navigate the history 
- [ ] Use a service to flush the content on the IPFS network 
- [ ] Run an IPFS node

The deployments history is only needed in special cases or for troubleshooting, all this content can be stored in an external service, and it can be decentralized like IPFS. Moving this content from the servers will help to release a lot of disk space and the history could still be find. Moving to IPFS we should consider if we should host our own IPFS node.

**Comment by pentreathm** [comment]
This work is being tracked here https://github.com/decentraland/catalyst/issues/1067
