### ISSUE TITLE
NFT Emotes Entity

### ISSUE THREAD

**Issue by pentreathm** [decentraland/catalyst#1060]
- [x] https://github.com/decentraland/common-schemas/issues/65
- [x] https://github.com/decentraland/urn-resolver/issues/115
- [x] https://github.com/decentraland/content-validator/issues/48
- [x] https://github.com/decentraland/catalyst/issues/992
- [x] https://github.com/decentraland/catalyst/issues/993
- [x] https://github.com/decentraland/catalyst/issues/994
- [ ] https://github.com/decentraland/catalyst-api-specs/issues/27
- [ ] Define how to manage profiles that have NFT emotes using the Wearable Entity created for the MVFW

**Comment by pentreathm** [comment]
Moved to https://github.com/decentraland/catalyst/issues/1060
