### ISSUE TITLE
Decentraland Bundle

### ISSUE THREAD

**Issue by pentreathm** [decentraland/catalyst#1139]
The Catalyst concept is falling short and leading to some confusion. The idea of the catalyst owner repo is that it should be an easy recipe to start your own Decentraland instance, for the time being, this doesn't involve the Client or some external utilities such as the Market Place or the Builder. To move in that direction the Catalyst Owner repository should be renamed to `Decentraland Bundle` and this will imply updates in several places tp have it all with the correct references and avoid more confusion. 

- [ ] Rename Catalyst Owner to Decentraland Bundle and update the Readme file
- [ ] Update the Catalyst Readme https://github.com/decentraland/catalyst 
- [ ] Update the Architecture Repo https://github.com/decentraland/architecture 
- [ ] Update the Catalyst Deployment reference to the repository https://dcl.tools/ops/catalyst-deployments/-/blob/master/ec2.ts#L176 
- [ ] Update the Platform Playbooks references to prior Catalyst Owner 
- [ ] According to Github documentation, it is recommended to point the clones to the new URL, do this in all Catalyst instances  `git remote set-url origin new_url` - https://docs.github.com/en/repositories/creating-and-managing-repositories/renaming-a-repository 
- [ ] After everything is done, notify Catalyst Owner to update their instances with a step-by-step guide
