### ISSUE TITLE
Goerli

### ISSUE THREAD

**Issue by pentreathm** [decentraland/catalyst#1149]
Based on the upcoming deprecation of the Ropsten Testnet: 
https://blog.ethereum.org/2022/05/30/ropsten-merge-announcement/ 
The Lower Envs need to be migrated to use Goerli Test Net

- [x]  catalyst
- [x]  catalyst-api-specs
- [x]  @dcl/catalyst-contracts
- [x]  @dcl/content-validator
- [x]  @dcl/crypto
- [x]  @dcl/hashing
- [x]  @dcl/schemas
- [x]  @dcl/snapshots-fetcher
- [x]  @dcl/urn-resolver
- [x]  eth-connect
- [x]  @dcl/content-hash-tree
- [x]  @dcl/catalyst-storage
- [x]  lighthouse
- [x]  explorer-bff
- [x]  catalyst-owner
- [x]  catalyst-monitor
- [x]  catalyst-client

**Comment by marianogoldman** [comment]
Done
