### ISSUE TITLE
Hosted Scenes Preview

### ISSUE THREAD

**Issue by pentreathm** [decentraland/catalyst#1301]
New scenes preview server for content creators. 
The goal is to use the same workflow that content creators use to deploy scenes to a catalyst and avoid all the extra steps required to create a Heroku container to upload the scene. 

RFC 
- [x] https://github.com/decentraland/adr/pull/92

Phase 1 
- [x] Deploy scenes preview **mini comms** to prod  
- [x] Deploy scenes preview **content server** to prod 
- [x] Connect AB generator to that server

Explorer 
- [ ] https://github.com/decentraland/unity-renderer/issues/3139
- [ ] https://github.com/decentraland/unity-renderer/issues/3138
- [ ] Have a way to turn off the green walls around the limits of the scene 

SDK/Kernel/CLI
- [x] Deploy a server that can hold scenes
- [x] Make sure a proper comms schema works for that server (add to ADR)
- [ ] Mini map can be hidden (add to ADR)
- [x] Skybox is configurable (add to ADR)
- [ ] Scene loading can be shut down (add to ADR)
- [x] When exiting genesis city is loaded & default minimap & sky settings are restored (add to ADR)
- [x] A deployment can be loaded at the beginning (Onboarding tutuorial)
- [x] Metrics&Track events are sent using the identifier for the deployed scene

Phase 2
- [ ] Server Garbage collection

**Comment by pentreathm** [comment]
TBD how to handle places tab and `/goto` commands when inside a scene preview
