### ISSUE TITLE
Comms v3 Rollout

### ISSUE THREAD

**Issue by pentreathm** [decentraland/catalyst#1352]
- [x] Update peer-ec1 to use v3 with ah hosted LiveKit node 
- [x] Update peer-ec2 to use v3 with LiveKit Cloud
- [x] Update peer-wc1 to use v3 with LiveKit Cloud
- [x] Update peer-eu1 to use v3 with LiveKit Cloud
- [x] Update peer-ap1 to use v3 with LiveKit Cloud
- [x] Create an easy way to switch comms version for Catalyst Owner 
- [x] Create a communication plan for Catalyst Owners and needed steps to connect to a LiveKic Cluster
