### ISSUE TITLE
On Chain validations with Block Indexer

### ISSUE THREAD

**Issue by pentreathm** [decentraland/catalyst#1353]
### Block Indexer

- Make it production ready:
	- [x] Convert it to WKC.
	- [x] Add metrics (hits / misses).
	- [x] Release it.

### Content server (content validator)

- Blocks:
	- [x] Integrate [block-indexer](https://github.com/decentraland/block-indexer) to [content-validator](https://github.com/decentraland/content-validator/pull/126) and remove usages of TheGraph for block determination. Fix existing (broken) tests.
- Scenes
	- [x] Check land ownership with new onchain contracts.
- Wearables
	- [x] Check wearable deployments with new onchain contracts.
- Emotes
	- [x] Check emote deployments  with new onchain contracts.

#### Test 
- [x] Sync a node from Scratch doing on-chain validations with block indexer 

#### Release 
- [x] Add the validations to a Catalyst release
