### ISSUE TITLE
Create a resize texture lambda helper

### ISSUE THREAD

**Issue by eordano** [decentraland/catalyst#1411]
For performance reasons, the renderers would really benefit from offloading the work of resizing textures (images) on the clientside. Most importantly, this is repeated work that all clients need to do multiple times when loading a texture.

Instead of doing this work many times, there are at least two points where we could tackle this issue:

* When a scene is getting deployed, optimize the asset to the size most preferable to the renderers (i.e., in a square-sized image with a power-of-two length)
* Provide a lambda service to avoid extra work on the renderers

While the first one requires that all creators re-deploy their scenes, the second solution could be a low-cost first approach to solve the missed frames seen in production. It would also save bandwidth; as some creators are posting extremely outsized images that end up being shrink by a great factor.

Specification:
* Provide an endpoint `/lambdas/content/{hash}/dxt/{length}` that returns the content stored by hash, resized to be {length}x{length} pixels, where {length} can be a power of two between 128 and 2048, using dxt compression/encoding

Abuse prevention:
* By caching the result (even if it's an error -- the hash could point to a resource that is not an image), this is similar to serve normal content, so we shouldn't have any particular network problem that is not general to all `/content/contents/` endpoints

**Comment by aleortega** [comment]
**Status update**

Pendings:
- [ ] Add new property relating original size with new size
- [ ] Write document detailing the auth options
- [ ] Implement auth workflow
- [ ] Implement cache to also cache error conversions

**Comment by pentreathm** [comment]
This initiative was moved to the Client side 
https://github.com/decentraland/unity-renderer/issues/4576
