### ISSUE TITLE
Realm Scoring: Impl

### ISSUE THREAD

**Issue by pentreathm** [decentraland/catalyst#1466]
Implement the Improvements defined 
https://github.com/decentraland/catalyst/issues/1075

**Comment by aleortega** [comment]
**Implementation Plan**

ETA March 31st:
- [ ] Update BFF to expose /about endpoint returning accepting_users boolean property
- [ ] Add new filter rule based on resources (RAM and CPU) on unity-renderer
- [ ] Add metrics measuring how long it takes to pick a realm (expose invariant, realm picked and the link which decided)

ETA April 7th:
- [ ] Add Catalyst Version link on unity-renderer (checking comms, lambdas, lamb2 and catalysts versions)
- [ ] Write down the invariants proposal on a technical document
- [ ] Add different invariants configuration agreed on the technical document
- [ ] Add force catalyst link rule (e.g: hela:heimdalr:baldr)
- [ ] Create dashboard in Grafana to track Pick Realm algorithm performance

**Comment by aleortega** [comment]
The two items dropped will be added when we migrate this algorithm to its own service int he scope of the following issue -> https://github.com/orgs/decentraland/projects/22/views/10?filterQuery=Realm&pane=issue&itemId=25045219
