### ISSUE TITLE
Comms Crash

### ISSUE THREAD

**Issue by pentreathm** [decentraland/catalyst#1483]
User communication connections are being lost and reconnected to the same realm in a loop. 

- [x] Bump LiveKit SDK Lib https://github.com/decentraland/unity-renderer/pull/4793   
- [x] Patch for Realm reconnections retry https://github.com/decentraland/unity-renderer/pull/4797 
- [x] Add logging https://github.com/decentraland/unity-renderer/pull/4798/ 
- [x] Make profiles updates lossy instead of reliable  https://github.com/decentraland/unity-renderer/pull/4801  - https://docs.livekit.io/client/data-messages/ 
- [x] Don not allow a second session tab to be opened at the same time https://github.com/decentraland/unity-renderer/pull/4804 
- [x] Clean up disconnection errors https://github.com/decentraland/unity-renderer/pull/4693 
- [x] Add LiveKit session details for troubleshooting with the LiveKit team https://github.com/decentraland/unity-renderer/commit/78a826538894c5a4a8242af6e736af685c10140b 
- [x] Remove noise from the console https://github.com/decentraland/unity-renderer/pull/4806 
- [x] Avoid sending messages when the connection is not available https://github.com/decentraland/unity-renderer/pull/4869  
- [x] Voice Chat handler improvements on the client https://github.com/decentraland/unity-renderer/pull/4873
