### ISSUE TITLE
DAO Proposals

### ISSUE THREAD

**Issue by pentreathm** [decentraland/catalyst#1514]
Tasks:
- [x] Propose to remove GET /lambdas/health & GET /lambdas/profiles 
- [x] Propose to remove GET /lambdas/contentv2/parcel_info & GET /lambdas/contentv2/contents/:cid & GET /lambdas/contentv2/scenes
- [x] Propose to remove GET /lambdas/collections/wearables-by-owner/{address}
