### ISSUE TITLE
Rate Limit using JWT

### ISSUE THREAD

**Issue by agusaldasoro** [decentraland/catalyst#522]
Pending tasks:
- [ ] [Explorer: get JWT Cookie](https://github.com/decentraland/explorer/pull/2514)
- [ ] Update Explorer to use cookies when making requests to Catalyst, this means adding the option: { credentials: 'include' }. This is blocked until every Catalyst implements Cors with dynamic origin.
- [ ] Make rates configurable through the `.env` file instead of them being part of the catalyst-owner repository to let Catalysts' owners quickly change the configuration.
